### ISSUE TITLE
Broken login

### ISSUE THREAD

**Issue by arn4** [ahivert/tgtg-python#326]
Since yesterday afternoon I am having some problems in login into the portal using this package. Here are some error messages I got for different API calls:
```
Traceback (most recent call last):
  File "/home/lucaarnaboldi/toogoodtoogo-bot/file.py", line 191, in <module>
    credentials = client.get_credentials()
  File "/home/lucaarnaboldi/toogoodtoogo-bot/tgtg/__init__.py", line 98, in get_credentials
    self.login()
  File "/home/lucaarnaboldi/toogoodtoogo-bot/tgtg/__init__.py", line 189, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/authByEmail.","instance":"/api/auth/v3/authByEmail"}')
```

```
Traceback (most recent call last):
  File "/home/lucaarnaboldi/toogoodtoogo-bot/tgtg/__init__.py", line 284, in get_item
    self.login()
  File "/home/lucaarnaboldi/toogoodtoogo-bot/tgtg/__init__.py", line 160, in login
    self._refresh_token()
  File "/home/lucaarnaboldi/toogoodtoogo-bot/tgtg/__init__.py", line 146, in _refresh_token
    raise TgtgAPIError(response.status_code, response.content)
tgtg.exceptions.TgtgAPIError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/token/refresh.","instance":"/api/auth/v3/token/refresh"}')
```

I guess something changed on the TGTG side. Can I help in fixing this?

**Comment by Palisand** [comment]
Same here. If someone can point me in the right direction, I can look into TGTG's updated API. I'm guessing I'd have to inspect outgoing requests while using the app on my phone?

**Comment by Palisand** [comment]
Oh perhaps this was fixed: https://github.com/ahivert/tgtg-python/commit/af0a9b5fc4d2960e4b21a168b88b4a1010b137a6

**Comment by Palisand** [comment]
This should be fixed as of [0.18.0](https://github.com/ahivert/tgtg-python/releases/tag/0.18.0).

**Comment by bbouretdev** [comment]
How should I proceed to upgrade the client version?
I currently use "pip install tgtg" as a command before each script execution, but still get this kind of error : "tgtg.exceptions.TgtgAPIError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/token/refresh.","instance":"/api/auth/v3/token/refresh"}')"

**Comment by oxamafia** [comment]
Hello
First of all thanx a lot for all the work done on this API! ☺️
I have the same issue and 0.18.0 doesn’t solve the problems unfortunately

**Comment by xxcite** [comment]
Hi,

currently, I also have issues with login. When I create the client with my e-mail address using
```
client = TgtgClient(email=myemail)
tgtg_creds = client.get_credentials()
```
I sometimes get the e-Mail and the login succeeds, but the client waits and finally runs into a timeout.

**Comment by arn4** [comment]
@Palisand I am using version `0.18.0` and I get the problem, so it not solved in the latests release

**Comment by maierfelix** [comment]
It seems like that the TGTG API now enforces the latest app version.

For the user agent I now use `TGTG/24.11.0`.

New authentication endpoints that work for me are:
````
auth/v5/authByEmail
auth/v5/authByRequestPin
auth/v5/authByRequestPollingId
auth/v5/token/refresh/
````

The only change that I've noticed is that the response after e-mail authentication no longer seems to include a `user_id` property.

Because of the missing `user_id`, for fetching favorite items I've switched to the `discover/v1/bucket` API endpoint, which doesn't require a `user_id`. The API design is similar to `item/v8/`, but has a few differences.

`discover/v1/bucket` expects a request in the following format:
````json
"origin": {"latitude": 0, "longitude": 0},
"radius": 10.0,
"paging": {"page":0, "size":50},
"bucket":{"filler_type": "Favorites"}
````
and it's response remains mostly the same, except the items array switched from `response.data.items` to `response.data.mobile_bucket.items`.

Regarding the manufacturer API, the following request structure is now required. Note the empty `query` property, which if missing always triggers a captcha error for me.
````json
"display_types_accepted":["LIST","FILL"],
"element_types_accepted":["ITEM","NPS","HIGHLIGHTED_ITEM","PARCEL_TEXT","DUO_ITEMS_V2","MANUFACTURER_STORY_CARD","SMALL_CARDS_CAROUSEL","ITEM_CARDS_CAROUSEL","HIGHLIGHTED_ITEM_CARDS_CAROUSEL"],
"action_types_accepted":["QUERY"],
"query":""
````

**Comment by ahivert** [comment]
@maierfelix could you open a PR with the changes you suggest ?

**Comment by ahivert** [comment]
@maierfelix the user agent is automatically retrieved from playstore when the client is built. Tested and it returns 24.11.0 :heavy_check_mark: 

fir the version API, v4 works well on my side. I can get_items() with a fresh client.

Things related to user_id that do not exists anymore are already available on release 0.18.0

**Comment by Palisand** [comment]
@arn4 Your posted error messages is a 404 for the route `/api/auth/v3/token/refresh`. I was getting the same thing before upgrading to 0.18.0, which uses the v4 API. 

Are you seeing `v4` in your error message after upgrading to 0.18.0?

**Comment by Palisand** [comment]
@xxcite I get that sometimes as well and I doubt there is much anyone here can do about that besides increase the polling time. It's up to TGTG to improve the speed of the delivery of their login emails.

**Comment by ahivert** [comment]
published a new version 0.18.1 to update api version. Could fix things or at least delay future errors

```
AUTH_BY_EMAIL_ENDPOINT = "auth/v5/authByEmail"
AUTH_POLLING_ENDPOINT = "auth/v5/authByRequestPollingId"
SIGNUP_BY_EMAIL_ENDPOINT = "auth/v5/signUpByEmail"
REFRESH_ENDPOINT = "auth/v5/token/refresh"
ACTIVE_ORDER_ENDPOINT = "order/v8/active"
INACTIVE_ORDER_ENDPOINT = "order/v8/inactive"
CREATE_ORDER_ENDPOINT = "order/v8/create/"
ABORT_ORDER_ENDPOINT = "order/v8/{}/abort"
ORDER_STATUS_ENDPOINT = "order/v8/{}/status"
```

**Comment by oxamafia** [comment]
Worked for me thanx a lot

**Comment by sirsquall** [comment]
How do you intsall the new version using pip? I tried pip install tgtg=0.18.1 but is not working, (sorry not a python dev, but i'm learning ahah)

**Comment by arn4** [comment]
On my side, it is now working, so the issue can be closed. Thank you all

**Comment by Jabei1969** [comment]
I've got a bit confused with the thread. I have updated to 0.18.1 & then reinstalled the Amin add-on. I still get the error 


Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/app/toogoodtogo_ha_mqtt_bridge/main.py", line 324, in fetch_loop
    tgtg_client.login()
  File "/usr/local/lib/python3.11/site-packages/tgtg/__init__.py", line 168, in login
    raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (404, b'{"type":"about:blank","title":"Not Found","status":404,"detail":"No static resource auth/v3/authByEmail.","instance":"/api/auth/v3/authByEmail"}')


Have I missed out something?

**Comment by sirsquall** [comment]
I have run : 
curl -k https://bootstrap.pypa.io/get-pip.py | python3
python3 -m pip install tgtg==0.18.1

and I got this error:
ERROR: No matching distribution found for tgtg==0.18.1

I'm still in the 0.17, should I do something more?

**Comment by sirsquall** [comment]
for those who got the same issue, the new version of tgtg 0.18.1 require at least python3.9
